<!DOCTYPE html>
<html lang="">
<head>
  <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2">
<meta name="theme-color" content="#222">
<meta name="generator" content="Hexo 3.7.1">
  <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-next.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32-next.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16-next.png">
  <link rel="mask-icon" href="/images/logo.svg" color="#222">

<link rel="stylesheet" href="/css/main.css">


<link rel="stylesheet" href="/lib/font-awesome/css/font-awesome.min.css">

<script id="hexo-configurations">
    var NexT = window.NexT || {};
    var CONFIG = {"hostname":"invicsfate.github.io","root":"/","scheme":"Pisces","version":"7.8.0","exturl":false,"sidebar":{"position":"right","display":"post","padding":18,"offset":12,"onmobile":false},"copycode":{"enable":false,"show_result":false,"style":null},"back2top":{"enable":true,"sidebar":false,"scrollpercent":false},"bookmark":{"enable":false,"color":"#222","save":"auto"},"fancybox":false,"mediumzoom":false,"lazyload":false,"pangu":false,"comments":{"style":"tabs","active":null,"storage":true,"lazyload":false,"nav":null},"algolia":{"hits":{"per_page":10},"labels":{"input_placeholder":"Search for Posts","hits_empty":"We didn't find any results for the search: ${query}","hits_stats":"${hits} results found in ${time} ms"}},"localsearch":{"enable":false,"trigger":"auto","top_n_per_article":1,"unescape":false,"preload":false},"motion":{"enable":true,"async":false,"transition":{"post_block":"fadeIn","post_header":"slideDownIn","post_body":"slideDownIn","coll_header":"slideLeftIn","sidebar":"slideUpIn"}}};
  </script>

  <meta name="description" content="​    自己用过很多次setUnhandleExceptionFilter出过题目了，题目的思路通常都是突然来一个异常，使得程序最终跳转到setUnhandleExceptionFilter的自定义异常函数中。当然，在调试状态下，如果在自定义异常函数中下断是没法直接到达的，原始是存在系统反调试。 ​    对于怎么绕过，自己一直都没有亲自去调试，只依稀有个印象-程序存在系统反调试。 ​    下">
<meta name="keywords" content="reverse">
<meta property="og:type" content="article">
<meta property="og:title" content="setUnhandleExceptionFilter-exploration">
<meta property="og:url" content="http://Invicsfate.github.io/2018/05/29/setUnhandleExceptionFilter-exploration/index.html">
<meta property="og:site_name" content="Invicsfate">
<meta property="og:description" content="​    自己用过很多次setUnhandleExceptionFilter出过题目了，题目的思路通常都是突然来一个异常，使得程序最终跳转到setUnhandleExceptionFilter的自定义异常函数中。当然，在调试状态下，如果在自定义异常函数中下断是没法直接到达的，原始是存在系统反调试。 ​    对于怎么绕过，自己一直都没有亲自去调试，只依稀有个印象-程序存在系统反调试。 ​    下">
<meta property="og:locale" content="default">
<meta property="og:image" content="https://invicsfate.github.io/assert/exception1.png">
<meta property="og:image" content="https://invicsfate.github.io/assert/exception2.png">
<meta property="og:image" content="https://invicsfate.github.io/assert/exception3.png">
<meta property="og:image" content="https://invicsfate.github.io/assert/exception4.png">
<meta property="og:image" content="https://invicsfate.github.io/assert/exception5.png">
<meta property="og:image" content="https://invicsfate.github.io/assert/exception6.png">
<meta property="og:image" content="https://invicsfate.github.io/assert/exception7.png">
<meta property="og:image" content="https://invicsfate.github.io/assert/exception8.png">
<meta property="og:image" content="https://invicsfate.github.io/assert/exception9.png">
<meta property="og:image" content="https://invicsfate.github.io/assert/exception10.png">
<meta property="og:image" content="https://invicsfate.github.io/assert/exception11.png">
<meta property="og:image" content="https://invicsfate.github.io/assert/exception12.png">
<meta property="og:image" content="https://invicsfate.github.io/assert/exception13.png">
<meta property="og:image" content="https://invicsfate.github.io/assert/exception14.png">
<meta property="og:image" content="https://invicsfate.github.io/assert/exception15.png">
<meta property="og:updated_time" content="2018-10-09T14:49:20.347Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="setUnhandleExceptionFilter-exploration">
<meta name="twitter:description" content="​    自己用过很多次setUnhandleExceptionFilter出过题目了，题目的思路通常都是突然来一个异常，使得程序最终跳转到setUnhandleExceptionFilter的自定义异常函数中。当然，在调试状态下，如果在自定义异常函数中下断是没法直接到达的，原始是存在系统反调试。 ​    对于怎么绕过，自己一直都没有亲自去调试，只依稀有个印象-程序存在系统反调试。 ​    下">
<meta name="twitter:image" content="https://invicsfate.github.io/assert/exception1.png">

<link rel="canonical" href="http://Invicsfate.github.io/2018/05/29/setUnhandleExceptionFilter-exploration/">


<script id="page-configurations">
  // https://hexo.io/docs/variables.html
  CONFIG.page = {
    sidebar: "",
    isHome : false,
    isPost : true,
    lang   : 'default'
  };
</script>

  <title>setUnhandleExceptionFilter-exploration | Invicsfate</title>
  






  <noscript>
  <style>
  .use-motion .brand,
  .use-motion .menu-item,
  .sidebar-inner,
  .use-motion .post-block,
  .use-motion .pagination,
  .use-motion .comments,
  .use-motion .post-header,
  .use-motion .post-body,
  .use-motion .collection-header { opacity: initial; }

  .use-motion .site-title,
  .use-motion .site-subtitle {
    opacity: initial;
    top: initial;
  }

  .use-motion .logo-line-before i { left: initial; }
  .use-motion .logo-line-after i { right: initial; }
  </style>
</noscript>

</head>

<body itemscope itemtype="http://schema.org/WebPage">
  <div class="container use-motion">
    <div class="headband"></div>

    <header class="header" itemscope itemtype="http://schema.org/WPHeader">
      <div class="header-inner"><div class="site-brand-container">
  <div class="site-nav-toggle">
    <div class="toggle" aria-label="Toggle navigation bar">
      <span class="toggle-line toggle-line-first"></span>
      <span class="toggle-line toggle-line-middle"></span>
      <span class="toggle-line toggle-line-last"></span>
    </div>
  </div>

  <div class="site-meta">

    <a href="/" class="brand" rel="start">
      <span class="logo-line-before"><i></i></span>
      <h1 class="site-title">Invicsfate</h1>
      <span class="logo-line-after"><i></i></span>
    </a>
      <p class="site-subtitle" itemprop="description">菜狗.jpg</p>
  </div>

  <div class="site-nav-right">
    <div class="toggle popup-trigger">
    </div>
  </div>
</div>




<nav class="site-nav">
  <ul id="menu" class="menu">
        <li class="menu-item menu-item-home">

    <a href="/" rel="section"><i class="fa fa-fw fa-home"></i>Home</a>

  </li>
        <li class="menu-item menu-item-archives">

    <a href="/archives/" rel="section"><i class="fa fa-fw fa-archive"></i>Archives</a>

  </li>
  </ul>
</nav>




</div>
    </header>

    
  <div class="back-to-top">
    <i class="fa fa-arrow-up"></i>
    <span>0%</span>
  </div>


    <main class="main">
      <div class="main-inner">
        <div class="content-wrap">
          

          <div class="content post posts-expand">
            

    
  
  
  <article itemscope itemtype="http://schema.org/Article" class="post-block" lang="default">
    <link itemprop="mainEntityOfPage" href="http://Invicsfate.github.io/2018/05/29/setUnhandleExceptionFilter-exploration/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="image" content="/images/avatar.gif">
      <meta itemprop="name" content="Invicsfate">
      <meta itemprop="description" content="如果你喜欢，就把这一切当作是荣耀，而不是炫耀--by 叶修">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="Invicsfate">
    </span>
      <header class="post-header">
        <h1 class="post-title" itemprop="name headline">
          setUnhandleExceptionFilter-exploration
        </h1>

        <div class="post-meta">
            <span class="post-meta-item">
              <span class="post-meta-item-icon">
                <i class="fa fa-calendar-o"></i>
              </span>
              <span class="post-meta-item-text">Posted on</span>

              <time title="Created: 2018-05-29 19:11:34" itemprop="dateCreated datePublished" datetime="2018-05-29T19:11:34+08:00">2018-05-29</time>
            </span>
              <span class="post-meta-item">
                <span class="post-meta-item-icon">
                  <i class="fa fa-calendar-check-o"></i>
                </span>
                <span class="post-meta-item-text">Edited on</span>
                <time title="Modified: 2018-10-09 22:49:20" itemprop="dateModified" datetime="2018-10-09T22:49:20+08:00">2018-10-09</time>
              </span>
            <span class="post-meta-item">
              <span class="post-meta-item-icon">
                <i class="fa fa-folder-o"></i>
              </span>
              <span class="post-meta-item-text">In</span>
                <span itemprop="about" itemscope itemtype="http://schema.org/Thing">
                  <a href="/categories/others/" itemprop="url" rel="index"><span itemprop="name">others</span></a>
                </span>
            </span>

          

        </div>
      </header>

    
    
    
    <div class="post-body" itemprop="articleBody">

      
        <p>​    自己用过很多次setUnhandleExceptionFilter出过题目了，题目的思路通常都是突然来一个异常，使得程序最终跳转到setUnhandleExceptionFilter的自定义异常函数中。当然，在调试状态下，如果在自定义异常函数中下断是没法直接到达的，原始是存在系统反调试。</p>
<p>​    对于怎么绕过，自己一直都没有亲自去调试，只依稀有个印象-程序存在系统反调试。</p>
<p>​    下面我们就来探究一下怎么绕过系统反调试，到达setUnhandleExceptionFilter的自定义异常函数。实验代码如下，实验工具x64dbg，如果没有某个库的符号，需要进行下载，便于动态调试。</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line">LONG _<span class="function">stdcall <span class="title">MyUnhandledExceptionFilter</span><span class="params">(_EXCEPTION_POINTERS *pExceptionInfo)</span></span></span><br><span class="line"><span class="function"></span>&#123;</span><br><span class="line">	MessageBox(<span class="literal">NULL</span>, <span class="string">L"UnhandleExceptionFileter"</span>,<span class="string">L"exception"</span>, MB_OK);</span><br><span class="line">	ExitProcess(<span class="number">0</span>);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">int</span> <span class="title">main</span><span class="params">()</span></span></span><br><span class="line"><span class="function"></span>&#123;</span><br><span class="line">	<span class="built_in">printf</span>(<span class="string">"Hello World!\n"</span>);</span><br><span class="line">	<span class="keyword">int</span> a = <span class="number">0</span>, b = <span class="number">100</span>, c;</span><br><span class="line">	SetUnhandledExceptionFilter(MyUnhandledExceptionFilter);</span><br><span class="line">	c = a + b;</span><br><span class="line">	c /= a;</span><br><span class="line">    <span class="keyword">return</span> <span class="number">0</span>;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>​    在将要产生异常的地方下断，便于我们调试。</p>
<p><img src="https://invicsfate.github.io/assert/exception1.png" alt="exception1"></p>
<p>​    同时将seh链的所有异常处理函数下断，我们已经只有在执行了seh链异常处理函数以后才会执行setUnhandledExceptionFilter注册的函数。</p>
<p><img src="https://invicsfate.github.io/assert/exception2.png" alt="exception2"></p>
<p>​    异常处理函数从上到下执行，顺序依次是0x00FB6140-&gt;0x00FB3D70-&gt;0x77CF9FD0。</p>
<p>​    发生异常以后，我们来到第一处seh异常处理函数0x00FB6140。</p>
<p><img src="https://invicsfate.github.io/assert/exception3.png" alt="exception3"></p>
<p>​    实现Jmp以后，我们继续F8执行，来到如下图的位置：</p>
<p><img src="https://invicsfate.github.io/assert/exception4.png" alt="exception4"></p>
<p>​    程序首先执行RtlIsValidHandler判断我们的下一出seh是否合法，然后调用RtlExecuteHandlerForException跳转到我们下一出seh函数地址，其中的第5个参数就是我们的下一处异常处理函数地址0x00FB3D70。我们接着进入RtlExecuteHandlerForException，看看他是怎么实现跳转的。</p>
<p><img src="https://invicsfate.github.io/assert/exception5.png" alt="exception5"></p>
<p>​    继续执行。</p>
<p><img src="https://invicsfate.github.io/assert/exception6.png" alt="exception6"></p>
<p>​    通过mov ecx,dword ptr ss:[ebp+18]将第五个参数即我们下一处seh函数地址给了ecx，然后调用。</p>
<p>​    我们来到第二处异常函数地址0x00FB3D70处，第二处进入第三处的调用过程基本一致。</p>
<p><img src="https://invicsfate.github.io/assert/exception7.png" alt="exception7"></p>
<p>​    我们单步到达上一次到达的RtlIsValidHandler处：</p>
<p><img src="https://invicsfate.github.io/assert/exception8.png" alt="exception8"></p>
<p>​    同理到达第三处，进入except_handler4_common：</p>
<p><img src="https://invicsfate.github.io/assert/exception9.png" alt="exception9"></p>
<p>​    进入CallFilterFunc函数：</p>
<p><img src="https://invicsfate.github.io/assert/exception10.png" alt="exception10"></p>
<p>​    进入第一个call ecx:</p>
<p><img src="https://invicsfate.github.io/assert/exception11.png" alt="exception11"></p>
<p>​    <img src="https://invicsfate.github.io/assert/exception12.png" alt="exception12"></p>
<p>​    在上图中，将RtlpUnhandleExceptionFilter带入函数RtlDecodePointer中解析，得到了UnhandlerExceptionFilter的函数地址，最后赋值给了esi，然后调用。</p>
<p>​    在UnhandlerExceptionFilter函数中，我们通过单步过掉不重要的函数以后，发现了一个可疑函数BasepIsDebugPortPresent，进入，找到了关键的反调试点，如下图：</p>
<p><img src="https://invicsfate.github.io/assert/exception13.png" alt="exception13"></p>
<p>​    如果处于调试中，esi的值会自加1，然后赋值给eax，返回。我们只需要将返回值改为0即可。</p>
<p>​    emmmm，然后我们就能顺利到达最后我们自己创建的那个异常处理函数了。</p>
<p><img src="https://invicsfate.github.io/assert/exception14.png" alt="exception14"></p>
<p><img src="https://invicsfate.github.io/assert/exception15.png" alt="exception15"></p>
<p>​    如上图，以后遇到类似的反调试，只需要在NtQueryInformationProcess函数下断就好了。如果写插件绕过，我们可以通过hook BasepIsDebugPortPresent(kernelbase.dll)函数，让其直接返回0即可。</p>

    </div>

    
    
    

      <footer class="post-footer">
          <div class="post-tags">
              <a href="/tags/reverse/" rel="tag"># reverse</a>
          </div>

        


        
    <div class="post-nav">
      <div class="post-nav-item">
    <a href="/2018/04/13/HITBCTF2018-reverse-hex/" rel="prev" title="HITBCTF2018-reverse-hex">
      <i class="fa fa-chevron-left"></i> HITBCTF2018-reverse-hex
    </a></div>
      <div class="post-nav-item">
    <a href="/2018/05/30/腾讯游戏安全2018/" rel="next" title="腾讯游戏安全2018">
      腾讯游戏安全2018 <i class="fa fa-chevron-right"></i>
    </a></div>
    </div>
      </footer>
    
  </article>
  
  
  



          </div>
          

<script>
  window.addEventListener('tabs:register', () => {
    let { activeClass } = CONFIG.comments;
    if (CONFIG.comments.storage) {
      activeClass = localStorage.getItem('comments_active') || activeClass;
    }
    if (activeClass) {
      let activeTab = document.querySelector(`a[href="#comment-${activeClass}"]`);
      if (activeTab) {
        activeTab.click();
      }
    }
  });
  if (CONFIG.comments.storage) {
    window.addEventListener('tabs:click', event => {
      if (!event.target.matches('.tabs-comment .tab-content .tab-pane')) return;
      let commentClass = event.target.classList[1];
      localStorage.setItem('comments_active', commentClass);
    });
  }
</script>

        </div>
          
  
  <div class="toggle sidebar-toggle">
    <span class="toggle-line toggle-line-first"></span>
    <span class="toggle-line toggle-line-middle"></span>
    <span class="toggle-line toggle-line-last"></span>
  </div>

  <aside class="sidebar">
    <div class="sidebar-inner">

      <ul class="sidebar-nav motion-element">
        <li class="sidebar-nav-toc">
          Table of Contents
        </li>
        <li class="sidebar-nav-overview">
          Overview
        </li>
      </ul>

      <!--noindex-->
      <div class="post-toc-wrap sidebar-panel">
      </div>
      <!--/noindex-->

      <div class="site-overview-wrap sidebar-panel">
        <div class="site-author motion-element" itemprop="author" itemscope itemtype="http://schema.org/Person">
  <p class="site-author-name" itemprop="name">Invicsfate</p>
  <div class="site-description" itemprop="description">如果你喜欢，就把这一切当作是荣耀，而不是炫耀--by 叶修</div>
</div>
<div class="site-state-wrap motion-element">
  <nav class="site-state">
      <div class="site-state-item site-state-posts">
          <a href="/archives/">
        
          <span class="site-state-item-count">34</span>
          <span class="site-state-item-name">posts</span>
        </a>
      </div>
      <div class="site-state-item site-state-categories">
        <span class="site-state-item-count">6</span>
        <span class="site-state-item-name">categories</span>
      </div>
      <div class="site-state-item site-state-tags">
        <span class="site-state-item-count">6</span>
        <span class="site-state-item-name">tags</span>
      </div>
  </nav>
</div>



      </div>

    </div>
  </aside>
  <div id="sidebar-dimmer"></div>


      </div>
    </main>

    <footer class="footer">
      <div class="footer-inner">
        

        

<div class="copyright">
  
  &copy; 
  <span itemprop="copyrightYear">2020</span>
  <span class="with-love">
    <i class="fa fa-user"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">Invicsfate</span>
</div>
  <div class="powered-by">Powered by <a href="https://hexo.io" class="theme-link" rel="noopener" target="_blank">Hexo</a> & <a href="https://pisces.theme-next.org" class="theme-link" rel="noopener" target="_blank">NexT.Pisces</a>
  </div>

        








      </div>
    </footer>
  </div>

  
  <script src="/lib/anime.min.js"></script>
  <script src="/lib/velocity/velocity.min.js"></script>
  <script src="/lib/velocity/velocity.ui.min.js"></script>
<script src="/js/utils.js"></script><script src="/js/motion.js"></script>
<script src="/js/schemes/pisces.js"></script>
<script src="/js/next-boot.js"></script>



  















  

  

</body>
</html>
